<html>
<head>
<title>Fenrir | Unified Defense Management Console</title>
<link rel='stylesheet' href='/static/css/style.css' type='text/css'/>
<link rel='stylesheet' href='/static/css/menu.css' type='text/css'/>
<link rel='stylesheet' href='/static/css/fonts.css' type='text/css'/>
<link rel="shortcut icon" href="/static/images/favicon.png" type="image/x-icon" />
<script src="/static/js/jquery-1.7.1.min.js"></script>
<script src="/static/js/jquery.mousewheel-min.js"></script>
<script src="/static/js/jquery.terminal-min.js"></script>
<link href="/static/css/jquery.terminal.css" rel="stylesheet">
<script src="/static/js/jquery.terminal-min.js"></script>
<link rel="stylesheet" href="/static/css/jquery-impromptu.min.css">
<script src="/static/js/jquery-impromptu.min.js"></script>
</head>
<body>