<!-- Navigation Pane --> 
<div id = "topnav">
   <div id = "nav_cont">
      <div id = "logo"><a href = "/"><img height = "50" src = "/static/images/favicon.png"></a></div>
         <div id = "navbar_cont">
            <a href = "/" class = "navbar">Dashboard</a>
            <a href = "/configure/" class = "navbar">Defense Console</a>
            <a href = "/sensors/" class = "navbar">Sensors</a>
            <a href = "/agents/" class = "navbar">Agents</a>
            <a href = "/appstore/" class = "navbar">Appstore</a>
         </div>
         <div id = "panel_menu">
            <a href="#" class = "panel_icons"><span class='icon-remove'></span></a>&nbsp;&nbsp;&nbsp;
            <a href="/configure/" class = "panel_icons"><span class='icon-shield'></span></a>&nbsp;&nbsp;&nbsp;
            <a href="#" class = "panel_icons"><span class='icon-share'></span></a>&nbsp;&nbsp;&nbsp;
            <a href = "/configure/" class = "panel_icons"><span class='icon-cog'></span></a>&nbsp;&nbsp;&nbsp;
         </div>
   </div>
   <!--
   <div id = "navbar">
      <div id = "navbar_cont">
         <a href = "/" class = "navbar">Dashboard</a>
         <a href = "/configure/" class = "navbar">Alerts</a>
         <a href = "/agents/" class = "navbar">Agents</a>
         <a href = "/appstore/" class = "navbar">Appstore</a>
      </div>
   </div>
   -->
</div>